
# =============================================================================
# 应用配置
# =============================================================================
[tool.app]
name = "Nuwa"
version = "1.0.0"
description = "智能AI插件管理和任务调度平台"
debug = true
host = "0.0.0.0"
port = 8000
environment = "development"
readme = "README.md"
authors = [
    { name = "Gordon", email = "Gordon@nuwa.com" }
]
license = { text = "MIT" }
requires_python = ">=3.9"
keywords = ["AI", "plugin", "automation", "task-scheduler"]