

# =============================================================================
# 数据库配置
# =============================================================================
[tool.database]
driver = "sqlite"
url = "sqlite+aiosqlite:///./data/nuwa.db"
pool_size = 10
max_overflow = 20
pool_timeout = 30
pool_recycle = 3600
pool_pre_ping = true
echo = false
