


# =============================================================================
# 日志配置
# =============================================================================
[logging]
level = "DEBUG"
format = "structured"
console = true
file_enabled = true
file_path = "./logs/app.log"
max_file_size = "10MB"
backup_count = 5